export const FETCH_LAKES = "FETCH_LAKES";
export const CURRENT_LAKE = "CURRENT_LAKE";
export const FAVORITED_LAKE = "FAVORITED_LAKES";
export const REMOVE_LAKE = "REMOVE_LAKE";


export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const POST_MESSAGE = "POST_MESSAGE";
export const PATCH_MESSAGE = "PATCH_MESSAGE";

export const POST_USER = "POST_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SHOW_LOGIN = "SHOW_LOGIN";
export const SHOW_SIGNUP = "SHOW_SIGNUP";

export const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS"
export const SET_SPECIES_FILTER = "SET_SPECIES_FILTER"
export const SET_LOCATION_FILTER = "SET_LOCATION_FILTER"
